/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jmaster.io.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jmaster.io.model.KhachHang;
import jmaster.io.service.KhachHangService;
import jmaster.io.utils.IDGenerator;
import jmaster.io.utils.Validator;

/**
 *
 * @author dinhd
 */
public class DanhSachKhachHangView extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachMatHang
     */
    public DanhSachKhachHangView() {
        initComponents();
        initScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rowPopupMenu = new javax.swing.JPopupMenu();
        deleteMenuItem = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        khTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maKHTxt = new javax.swing.JTextField();
        themBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loaixeThue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        soXeThue = new javax.swing.JTextField();
        hoTenTxt = new javax.swing.JTextField();

        deleteMenuItem.setText("Xoa");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        rowPopupMenu.add(deleteMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        khTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        khTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        khTable.setComponentPopupMenu(rowPopupMenu);
        khTable.setEditingRow(0);
        khTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(khTable);

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        backBtn.setText("Quay ve");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(153, 204, 255));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("loai xe thue");

        maKHTxt.setEditable(false);
        maKHTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        themBtn.setBackground(new java.awt.Color(153, 204, 255));
        themBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        themBtn.setText("Them KH");
        themBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Max KH");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Ho Ten");

        loaixeThue.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("so xe thue");

        soXeThue.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        hoTenTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soXeThue)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(themBtn)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(loaixeThue, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(hoTenTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(maKHTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(hoTenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loaixeThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(soXeThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(themBtn)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(maKHTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshBtn)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(refreshBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new MainView().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        refreshData();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtnActionPerformed
        themKhachHang();
    }//GEN-LAST:event_themBtnActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        deleteItem();
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JTextField loaixeThue;
    private javax.swing.JTextField hoTenTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable khTable;
    private javax.swing.JTextField maKHTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JPopupMenu rowPopupMenu;
    private javax.swing.JTextField soXeThue;
    private javax.swing.JButton themBtn;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel tableModel = new DefaultTableModel();
    private KhachHangService khachHangService = new KhachHangService();

    private void initScreen() {
        khTable.setModel(tableModel);
        //set ten cot
        tableModel.addColumn("Ma khach hang");
        tableModel.addColumn("Ho ten");
        tableModel.addColumn("Loai xe thue");
        tableModel.addColumn("So xe thue");
        //set du lieu
        refreshData();

        //set ID mac dinh
        maKHTxt.setText(String.valueOf(IDGenerator.getKHID()));
    }

    private void refreshData() {
        try {
            tableModel.setRowCount(0);//xoa du lieu cu

            ArrayList<KhachHang> khachHangList = khachHangService.findAll();

            for (KhachHang khachHang : khachHangList) {
                tableModel.addRow(new Object[]{
                    khachHang.getMaKH(),
                    khachHang.getHoTen(),
                    khachHang.getLoaiXeThue(),
                    khachHang.getSoXeThue()
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(DanhSachKhachHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void themKhachHang() {
        KhachHang khachHang = new KhachHang();

        khachHang.setMaKH(Integer.parseInt(maKHTxt.getText()));

        String hoTen = hoTenTxt.getText();
        if (Validator.isRequiredString(hoTen)) {
            khachHang.setHoTen(hoTen);
        } else {
            JOptionPane.showMessageDialog(this, "Vui long nhap lai", "Loi", JOptionPane.ERROR_MESSAGE);
            return;//ko cho chay tiep
        }

        String loaixe = loaixeThue.getText();
        if (Validator.isRequiredString(loaixe)) {
            khachHang.setLoaiXeThue(loaixe);
        } else {
            JOptionPane.showMessageDialog(this, "Vui long nhap lai", "Loi", JOptionPane.ERROR_MESSAGE);
            return;//ko cho chay tiep
        }

        String soXe = soXeThue.getText();
        if (Validator.isValidPhone(soXe)) {
            khachHang.setSoXeThue(Integer.parseInt(soXe));
        } else {
            JOptionPane.showMessageDialog(this, "Vui long nhap lai so xe thue", "Loi", JOptionPane.ERROR_MESSAGE);
            System.out.println(soXe);
            return;//ko cho chay tiep
        }

        try {
            khachHangService.create(khachHang);

            //reload lai data
            refreshData();
            //set ID mac dinh
            maKHTxt.setText(String.valueOf(IDGenerator.getKHID()));
        } catch (Exception ex) {
            Logger.getLogger(DanhSachKhachHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteItem() {
        int selectedRow = khTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui long chon dong du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Ban chac muon xoa");
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    //lay cot so 0 cua dong duoc chon chinh la cot MaKH
                    int maKH = (Integer) khTable.getValueAt(selectedRow, 0);
                    khachHangService.delete(maKH);

                    //reload lai data
                    refreshData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
}
