/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jmaster.io.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jmaster.io.model.DanhSachMuaHang;
import jmaster.io.model.KhachHang;
import jmaster.io.model.MatHang;
import jmaster.io.model.Oto;
import jmaster.io.service.DanhSachMuaHangService;
import jmaster.io.service.KhachHangService;
import jmaster.io.service.MatHangService;
import jmaster.io.utils.Validator;

/**
 *
 * @author dinhd
 */
public class DanhSachMuaHangView extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachMatHang
     */
    public DanhSachMuaHangView() {
        initComponents();
        initScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dsmhTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        sapXepTenKHBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        themMHBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        soLuongMuaTxt = new javax.swing.JTextField();
        mhComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        khComboBox = new javax.swing.JComboBox<>();
        sapXepTenMHBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsmhTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dsmhTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsmhTable.setEditingRow(0);
        dsmhTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(dsmhTable);

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        backBtn.setText("Quay ve");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        sapXepTenKHBtn.setBackground(new java.awt.Color(153, 204, 255));
        sapXepTenKHBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sapXepTenKHBtn.setText("Sap xep theo ten KH");
        sapXepTenKHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapXepTenKHBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mat hang");

        themMHBtn.setBackground(new java.awt.Color(153, 204, 255));
        themMHBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        themMHBtn.setText("Them DS");
        themMHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMHBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("So luong");

        soLuongMuaTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        mhComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Khach hang");

        khComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soLuongMuaTxt)
                    .addComponent(mhComboBox, 0, 350, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(themMHBtn)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(khComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(khComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soLuongMuaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(themMHBtn)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        sapXepTenMHBtn.setBackground(new java.awt.Color(153, 204, 255));
        sapXepTenMHBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sapXepTenMHBtn.setText("Sap xep theo ten kh");
        sapXepTenMHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapXepTenMHBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sapXepTenMHBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sapXepTenKHBtn)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(sapXepTenKHBtn)
                    .addComponent(sapXepTenMHBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new MainView().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void sapXepTenKHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapXepTenKHBtnActionPerformed
        sapXepTheoTenKH();
    }//GEN-LAST:event_sapXepTenKHBtnActionPerformed

    private void themMHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMHBtnActionPerformed
        themDSMH();
    }//GEN-LAST:event_themMHBtnActionPerformed

    private void sapXepTenMHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapXepTenMHBtnActionPerformed
        // TODO add your handling code here:
        sapXepTheoTenMH();
    }//GEN-LAST:event_sapXepTenMHBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable dsmhTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<KhachHang> khComboBox;
    private javax.swing.JComboBox<Oto> mhComboBox;
    private javax.swing.JButton sapXepTenKHBtn;
    private javax.swing.JButton sapXepTenMHBtn;
    private javax.swing.JTextField soLuongMuaTxt;
    private javax.swing.JButton themMHBtn;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel tableModel = new DefaultTableModel();
    private MatHangService matHangService = new MatHangService();
    private DanhSachMuaHangService danhSachMuaHangService = new DanhSachMuaHangService();
    private KhachHangService khachHangService = new KhachHangService();

    private void initScreen() {
        dsmhTable.setModel(tableModel);
        //set ten cot
        tableModel.addColumn("Ma kh");
        tableModel.addColumn("Ho ten");
        tableModel.addColumn("kieu xe");
        tableModel.addColumn("Gia thue");
        tableModel.addColumn("So luong xe");

        //load data khach hang, mat hang cho combo box
        loadKHData();
        loadMHData();
        
        //load du lieu mac dinh 
        sapXepTheoTenKH();
    }

    private void loadKHData() {
        try {
            ArrayList<KhachHang> khachHangList = khachHangService.findAll();

            for (KhachHang khachHang : khachHangList) {
                khComboBox.addItem(khachHang);
            }
        } catch (Exception ex) {
            Logger.getLogger(DanhSachKhachHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadMHData() {
        try {
            ArrayList<Oto> matHangList = matHangService.findAll();

            for (Oto matHang : matHangList) {
                mhComboBox.addItem(matHang);
            }
        } catch (Exception ex) {
            Logger.getLogger(DanhSachKhachHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void sapXepTheoTenKH() {
        try {
            tableModel.setRowCount(0);//xoa du lieu cu

            ArrayList<jmaster.io.model.DanhSachMuaHang> danhSachMuaHangs = danhSachMuaHangService.sortByTenKH();

            for (jmaster.io.model.DanhSachMuaHang dsmh : danhSachMuaHangs) {
                tableModel.addRow(new Object[]{
                    dsmh.getKhachHang().getMaKH(),
                    dsmh.getKhachHang().getHoTen(),
                    dsmh.getOto().getKieuXe(),
                    dsmh.getOto().getSoTienThue(),
                    dsmh.getSoLuong()
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(DanhSachMuaHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void sapXepTheoTenMH() {
        try {
            tableModel.setRowCount(0);//xoa du lieu cu

            ArrayList<DanhSachMuaHang> danhSachMuaHangs = danhSachMuaHangService.sortByTenMH();

            for (DanhSachMuaHang dsmh : danhSachMuaHangs) {
                tableModel.addRow(new Object[]{
                    dsmh.getKhachHang().getMaKH(),
                    dsmh.getKhachHang().getHoTen(),
                    dsmh.getOto().getKieuXe(),
                    dsmh.getOto().getSoTienThue(),
                    dsmh.getSoLuong()
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(DanhSachMuaHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lá»—i Ä‘á»�c dá»¯ liá»‡u", "Lá»—i", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void themDSMH() {
        DanhSachMuaHang dsmh = new DanhSachMuaHang();

        KhachHang khachHang = (KhachHang) khComboBox.getSelectedItem();
        dsmh.setKhachHang(khachHang);

        Oto matHang = (Oto) mhComboBox.getSelectedItem();
        dsmh.setOto(matHang);

        String soLuongMua = soLuongMuaTxt.getText();
        if (Validator.isValidInteger(soLuongMua)) {
            dsmh.setSoLuong(Integer.parseInt(soLuongMua));
        } else {
            JOptionPane.showMessageDialog(this, "Vui long nhap lai", "Loi", JOptionPane.ERROR_MESSAGE);
            return;//ko cho chay tiep
        }

        try {
            //kiem tra khach hang da mua mat hang chua
            if (Validator.validateDSMH(dsmh)) {
                danhSachMuaHangService.create(dsmh);

                //reload lai data
                sapXepTheoTenKH();
            } else {
                JOptionPane.showMessageDialog(this, "Mat hang da chon thue roi", "Loi", JOptionPane.ERROR_MESSAGE);
                return;//ko cho chay tiep
            }
        } catch (Exception ex) {
            Logger.getLogger(DanhSachMuaHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }
}
