/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jmaster.io.view;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jmaster.io.model.DanhSachMuaHang;
import jmaster.io.model.KhachHang;
import jmaster.io.service.DanhSachMuaHangService;
import jmaster.io.service.KhachHangService;

/**
 *
 * @author dinhd
 */
public class HoaDonView extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachMatHang
     */
    public HoaDonView() {
        initComponents();
        initScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dsmhTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        khComboBox = new javax.swing.JComboBox<>();
        timKHBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsmhTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dsmhTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsmhTable.setEditingRow(0);
        dsmhTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(dsmhTable);

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        backBtn.setText("Quay ve");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        khComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        timKHBtn.setBackground(new java.awt.Color(153, 204, 255));
        timKHBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        timKHBtn.setText("Tim kiem");
        timKHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKHBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Khach hang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(khComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timKHBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(khComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKHBtn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new MainView().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void timKHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKHBtnActionPerformed
        findHoaDon();
    }//GEN-LAST:event_timKHBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable dsmhTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<KhachHang> khComboBox;
    private javax.swing.JButton timKHBtn;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel tableModel = new DefaultTableModel();
    private DanhSachMuaHangService danhSachMuaHangService = new DanhSachMuaHangService();
    private KhachHangService khachHangService = new KhachHangService();

    private void initScreen() {
        dsmhTable.setModel(tableModel);
        //set ten cot
        tableModel.addColumn("Ma KH");
        tableModel.addColumn("Ho Ten");
        tableModel.addColumn("Kieu Xe");
        tableModel.addColumn("Gia Thue");
        tableModel.addColumn("So luong thue");
        
        //load data khach hang
        loadKHData();
    }
    
    private void loadKHData() {
        try {
            ArrayList<KhachHang> khachHangList = khachHangService.findAll();

            for (KhachHang khachHang : khachHangList) {
                khComboBox.addItem(khachHang);
            }
        } catch (Exception ex) {
            Logger.getLogger(DanhSachKhachHangView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void findHoaDon() {
        try {
            //doc khach hang tu combox ve
            KhachHang khachHang = (KhachHang) khComboBox.getSelectedItem();

            tableModel.setRowCount(0);//xoa du lieu cu

            ArrayList<DanhSachMuaHang> danhSachMuaHangs = danhSachMuaHangService.findByKH(khachHang.getMaKH());

            for (DanhSachMuaHang dsmh : danhSachMuaHangs) {
                tableModel.addRow(new Object[]{
                    dsmh.getKhachHang().getMaKH(),
                    dsmh.getKhachHang().getHoTen(),
                    dsmh.getOto().getKieuXe(),
                    dsmh.getOto().getSoTienThue(),
                    dsmh.getSoLuong()
                });
            }
            //ko co ds mua hang
            if (danhSachMuaHangs.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Khach hang chua co hoa don", "Thong Bao", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(HoaDonView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi doc du lieu", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }
}
